name: CICD-AUTO-UPLOAD-PLUGIN-WP
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install composer
        run: |
          composer install --no-scripts
          composer update
          composer dump-autoload
        #đổi tên thư mục đúng với tên plugin
        working-directory: './elementor/wil-featured-block'

      - name: SFTP Deploy
        uses: Creepios/sftp-action@v1.0.3
        with:
          username: 'root'
          host: '198.58.120.4'
          port: 22
          password: 'HktXQ2j,RYSj/,6-'
          #đổi tên thư mục đúng với tên plugin
          localPath: './elementor/wil-featured-block'
          #đổi tên thư mục đúng với tên plugin
          remotePath: '/var/www/magicbadges/wp-content/plugins/wil-featured-block'

          # sftp args
          args: '-o ConnectTimeout=5'
