name: CICD-AUTO-UPLOAD-PLUGIN-WP
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install composer
        run: |
          composer update
          composer dump-autoload
        #đổi tên thư mục đúng với tên plugin
        working-directory: './elementor/wil-card'

      - name: SFTP Deploy
        uses: Creepios/sftp-action@v1.0.3
        with:
          username: ${{ secrets.USER_PLUGIN }}
          host: ${{ secrets.HOST }}
          port: 22
          password: ${{ secrets.PASSWORD }}
          #đổi tên thư mục đúng với tên plugin
          localPath: './elementor/wil-card'
          #đổi tên thư mục đúng với tên plugin
          remotePath: '/var/www/plugins/wp-content/plugins/wil-card'

          # sftp args
          args: '-o ConnectTimeout=5'
